// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjCUlCUcED3Kwblvj9j0y2rUHW6UZ38N4',
    appId: '1:806765813970:web:d2419c66cfec2fd47d8d0b',
    messagingSenderId: '806765813970',
    projectId: 'bowling-assistant',
    authDomain: 'bowling-assistant.firebaseapp.com',
    storageBucket: 'bowling-assistant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACy7nmf277jxllntBQ9d7pr8vY4aVAVtw',
    appId: '1:806765813970:android:8a743cfa489ba25e7d8d0b',
    messagingSenderId: '806765813970',
    projectId: 'bowling-assistant',
    storageBucket: 'bowling-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzwXkMuMl7mQZWxC6IHHVhxSGRqbnWUpU',
    appId: '1:806765813970:ios:81246d97616319f07d8d0b',
    messagingSenderId: '806765813970',
    projectId: 'bowling-assistant',
    storageBucket: 'bowling-assistant.firebasestorage.app',
    iosBundleId: 'com.example.bowlingAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzwXkMuMl7mQZWxC6IHHVhxSGRqbnWUpU',
    appId: '1:806765813970:ios:81246d97616319f07d8d0b',
    messagingSenderId: '806765813970',
    projectId: 'bowling-assistant',
    storageBucket: 'bowling-assistant.firebasestorage.app',
    iosBundleId: 'com.example.bowlingAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjCUlCUcED3Kwblvj9j0y2rUHW6UZ38N4',
    appId: '1:806765813970:web:68a98929025d2d407d8d0b',
    messagingSenderId: '806765813970',
    projectId: 'bowling-assistant',
    authDomain: 'bowling-assistant.firebaseapp.com',
    storageBucket: 'bowling-assistant.firebasestorage.app',
  );

}